insert into Genre (genre, book_id) values
                                       ('Fiction', null),
                                       ('Non-Fiction', null),
                                       ('Science Fiction', null),
                                       ('Fantasy', null),
                                       ('Mystery', null),
                                       ('Thriller', null),
                                       ('Romance', null),
                                       ('Historical', null),
                                       ('Biography', null),
                                       ('Self-Help', null),
                                       ('Cookbook', null),
                                       ('Travel', null),
                                       ('Science', null),
                                       ('Childrens', null),
                                       ('Young Adult', null),
                                       ('Horror', null),
                                       ('Classic', null),
                                       ('Poetry', null),
                                       ('Adventure', null),
                                       ('Graphic Novel', null),
                                       ('Memoir', null),
                                       ('Philosophy', null),
                                       ('Religion', null),
                                       ('Health', null),
                                       ('Business', null),
                                       ('Politics', null),
                                       ('Psychology', null),
                                       ('Education', null),
                                       ('Art', null),
                                       ('Sports', null),
                                       ('Music', null),
                                       ('Technology', null);

INSERT INTO type (type, book_id) VALUES
                                     ('Educational', null),
                                     ('Popular science', null),
                                     ('Scientific', null),
                                     ('Reference', null),
                                     ('Fiction', null),
                                     ('Non-Fiction', null);